name: Request UI review

on:
  pull_request:
    types: [ labeled ]

jobs:
  publish:
    if: ${{ github.event.label.name == 'UI-review requested' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install packages
        run: yarn install --immutable

      - name: Generate styles
        run: yarn workspace @savelevmatthew/ui build:vars

      - name: Publish chromatic build
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: packages/ui


