name: Rebaser

on:
  push:
    branches:
      - design

jobs:
  generatePR:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout old branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Rebase
        run: |
          git rebase origin/main
          git push origin design:tokens --force

      


